# Generated by Django 4.2.6 on 2023-11-27 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_alter_detection_options_alter_pigeon_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='detection',
            options={},
        ),
        migrations.AddField(
            model_name='detection',
            name='confidence',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='detection',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='detection',
            name='most_confident_label',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='detection',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='detection',
            name='datetime',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Date and time of detection'),
        ),
    ]
