# Generated by Django 4.2.6 on 2023-11-27 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_remove_detection_video_alter_detection_latitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='detection',
            name='frame_image_detected',
            field=models.ImageField(null=True, upload_to='frames/'),
        ),
    ]
