# Generated by Django 4.2.6 on 2023-11-28 00:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0007_detection_image64'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detection',
            name='image64',
        ),
    ]
