# Generated by Django 4.2.6 on 2023-11-28 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0009_detection_image64'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detection',
            name='frame',
            field=models.ImageField(blank=True, null=True, upload_to='frames/'),
        ),
    ]
