# Generated by Django 4.2.6 on 2023-11-28 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0010_alter_detection_frame'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detection',
            name='image64',
        ),
        migrations.AlterField(
            model_name='detection',
            name='frame',
            field=models.ImageField(null=True, upload_to='frames/'),
        ),
    ]
