# Generated by Django 4.2.6 on 2023-11-28 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0012_alter_detection_frame'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detection',
            name='frame',
            field=models.ImageField(null=True, upload_to='frames/'),
        ),
    ]
